services:
  api:
    container_name: finnd-strompreisrechner-api
    image: finnd-strompreisrechner-api
    build:
      context: .
      dockerfile: FinnD.Strompreisrechner.Api/Dockerfile
    ports:
      - "5000:80"
    volumes:
      - "./data:/app/publish/history.db"
