// <auto-generated />
using System;
using FinnD.Strompreisrechner.Api.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FinnD.Strompreisrechner.Api.Migrations
{
    [DbContext(typeof(HistoryDbContext))]
    [Migration("20230420181334_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.5");

            modelBuilder.Entity("FinnD.Strompreisrechner.Api.Database.HistoryEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTime>("ErstelltAm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<decimal>("KwhVerbrauchProJahr")
                        .HasColumnType("TEXT")
                        .HasColumnName("kwh_per_year");

                    b.Property<decimal>("PricePerDay")
                        .HasColumnType("TEXT")
                        .HasColumnName("price_per_day");

                    b.Property<decimal>("PricePerHour")
                        .HasColumnType("TEXT")
                        .HasColumnName("price_per_hour");

                    b.Property<decimal>("PricePerKwh")
                        .HasColumnType("TEXT")
                        .HasColumnName("price_per_kwh");

                    b.Property<decimal>("PricePerMinute")
                        .HasColumnType("TEXT")
                        .HasColumnName("price_per_minute");

                    b.Property<decimal>("PricePerMonth")
                        .HasColumnType("TEXT")
                        .HasColumnName("price_per_month");

                    b.Property<decimal>("PricePerYear")
                        .HasColumnType("TEXT")
                        .HasColumnName("price_per_year");

                    b.HasKey("Id");

                    b.ToTable("history_entries", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
