// <auto-generated />
using System;
using FinnD.Strompreisrechner.Api.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FinnD.Strompreisrechner.Api.Migrations
{
    [DbContext(typeof(HistoryDbContext))]
    partial class HistoryDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.5");

            modelBuilder.Entity("FinnD.Strompreisrechner.Api.Database.HistoryEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<decimal>("KwhConsumptionPerYear")
                        .HasColumnType("TEXT")
                        .HasColumnName("kwh_per_year");

                    b.Property<decimal>("PricePerKwhInEuro")
                        .HasColumnType("TEXT")
                        .HasColumnName("price_per_kwh");

                    b.Property<decimal>("PricePerYearInEuro")
                        .HasColumnType("TEXT")
                        .HasColumnName("price_per_year");

                    b.HasKey("Id");

                    b.ToTable("history_entries", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
